### ISSUE TITLE
Fix SOIT error

### ISSUE THREAD

**Issue by tdivoll** [WilhelmusLab/ice-floe-tracker-pipeline#102]
When running SOIT from a task and using the Docker image for software, getting an error: 

```Traceback (most recent call last):
  File "/usr/local/bin/pass_time_cylc.py", line 487, in <module>
    main()
  File "/usr/local/bin/pass_time_cylc.py", line 482, in main
    get_passtimes(**vars(args))
  File "/usr/local/bin/pass_time_cylc.py", line 351, in get_passtimes
    if (pass_dict["rise_lat"] > pass_dict["over_lat"]) and (
KeyError: 'over_lat'
2024-01-19T12:53:04-05:00 CRITICAL - failed/ERR```

**Comment by tdivoll** [comment]
@danielmwatkins, have you gotten this error at all when running the SOIT script?

**Comment by danielmwatkins** [comment]
I haven’t, what are the case settings you were trying?-DanielOn Jan 19, 2024, at 13:07, Timothy Divoll ***@***.***> wrote:﻿
@danielmwatkins, have you gotten this error at all when running the SOIT script?

**Comment by tdivoll** [comment]
I seem to get it when running SOIT via Cylc on Oscar with the `bering_sea` set from the sample locations. @cpaniaguam reminded me that there is some discussion of this in the [SOIT repo:](https://github.com/WilhelmusLab/SOIT-Satellite-Overpass-Identification-Tool/issues/1).
I think it's just an issue with certain dates and certain overpass times.

**Comment by cpaniaguam** [comment]
> I seem to get it when running SOIT via Cylc on Oscar with the `bering_sea` set from the sample locations. @cpaniaguam reminded me that there is some discussion of this in the [SOIT repo:](https://github.com/WilhelmusLab/SOIT-Satellite-Overpass-Identification-Tool/issues/1). I think it's just an issue with certain dates and certain overpass times.

I could also be certain combos of lat/lon pairs.

**Comment by tdivoll** [comment]
```location,center_lat,center_lon,top_left_lat,top_left_lon,lower_right_lat,lower_right_lon,left_x,right_x,lower_y,top_y,startdate,enddate

bering_strait,65,-170,55.92827,-172.77869,74.25843,-163.83708,-3002871.001,-1502871.001,827477.2577,2327477.258,2020-09-04,2020-09-07```

**Comment by cpaniaguam** [comment]
Fixed in #156
